FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install psycopg2-binary
RUN pip install flask requests 

COPY app.py .
EXPOSE 5000 8000

CMD ["python", "app.py"]
#docker build -t my_app .
#docker run -d my_app